#Server
server:
  port: 9020
  servlet-path: /addressMigratorRemoteRepository
spring:
  application:
    name: address-migrator-remote-application
  batch:
    lightmin:
      server:
        url: http://localhost:50100/lightmin-server
      client:
        external-links:
          hystrix: http://localhost:${server.port}/hystrixdashboard
          batchtasks: http://localhost:${server.port}/batchtasks
      #default jdbc
      batch-repository-type: jdbc
      #default jdbc
      lightmin-repository-type: remote
      #default dataSource
      batch-data-source-name: dataSource
      #default BATCH_
      repository-table-prefix: BATCH_
      #remote repository server url
      remote-repository-server-url: http://localhost:50000
