#server
server:
  port: 50000
#spring boot
spring:
  application:
    name: remote-repository-server
#ligtmin
  batch:
     lightmin:
       remote:
         repository:
           server:
             lightmin-repository-type: jdbc
             #override the default table names
             job-configuration-table-name: job_configuration
             job-configuration-value-table-name: configuration_value
             job-configuration-parameter-table-name: configuration_parameter
