server:
  port: 50100
  servlet-path: /lightmin-server
spring:
  application:
    name: spring-batch-lightmin-server
  batch:
    job:
      enabled: false
    lightmin:
      lightmin-repository-type: map
      batch-repository-type: map
      server:
        url: http://localhost:50100/lightmin-server
        heartbeat-period: 1000